name: CI

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed

jobs:
  bump:
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}

    name: 'Pre-release bump'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'See refs'
        run: |
          echo ref: ${{ github.ref }}
          echo base: ${{ github.base_ref }}
          echo head: ${{ github.head_ref }}

      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: "Get commit info"
        id: commit-info
        run: |
          echo "sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

      - name: 'Bump version'
        id: version-bump
        uses: 'nahuelhds/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # See: https://github.com/phips28/gh-action-bump-version?tab=readme-ov-file#usage
          bump-policy: 'ignore'
          version-type: minor
          tag-suffix: -${{ github.event.pull_request.merged == true && 'beta' || 'alpha' }}+${{ steps.commit-info.outputs.sha }}
          # For features, we want to create the tag but not changing the package.json
          skip-commit: 'true'
          # Use skip-tag if you create the tag in another step of your workflow
          # skip-tag: 'true'

      - name: "cat package.json"
        run: cat package.json

      - name: 'Output Step'
        run: |
          echo TAG: ${{ steps.version-bump.outputs.newTag }}

  build:
    needs: bump
    name: "Build ${{ needs.bump.outputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Version built: ${{ needs.bump.outputs.version }}'
        run: |
          echo TAG: ${{ needs.bump.outputs.version }}
