name: Main CI

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - main

env:
  DEVELOP_BRANCH: develop
  MAIN_BRANCH: main

jobs:
  bump:
    if: ${{ github.event.pull_request.merged == true }}
    name: 'Final version'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ env.MAIN_BRANCH }}
          fetch-depth: 0

      - name: 'Final version'
        id: version-bump
        uses: 'nahuelhds/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: ${{ env.MAIN_BRANCH }}
          # See: https://github.com/phips28/gh-action-bump-version?tab=readme-ov-file#usage
          bump-policy: 'ignore'
          version-type: minor
          # Use skip-tag if you create the tag in another step of your workflow
          # skip-tag: 'true'

      - name: "cat package.json"
        run: cat package.json

      - name: 'Output Step'
        run: |
          echo TAG: ${{ steps.version-bump.outputs.newTag }}

  build:
    needs: bump
    name: "Build ${{ needs.bump.outputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Version built: ${{ needs.bump.outputs.version }}'
        run: |
          echo TAG: ${{ needs.bump.outputs.version }}

  clean-tags:
    needs:
      - bump
      - build
    name: "Clean tags"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ env.MAIN_BRANCH }}
          fetch-depth: 0

      - name: Clean "${{ needs.bump.outputs.version }}-*" tags
        run: |
          git tag | grep ${{ needs.bump.outputs.version }}- | xargs -n 1 -I% git push origin :refs/tags/%

  pr-to-develop:
    name: "PR to develop"
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Reference: https://cli.github.com/manual/gh_pr_create
        run: |
          gh pr create --title "Backport: ${{ needs.bump.outputs.version }}..${{ env.DEVELOP_BRANCH }}" --body "Backport for ${{ needs.bump.outputs.version }}" --base ${{ env.DEVELOP_BRANCH }}
