name: Backport CI

on:
  push:
    branches:
      - main

env:
  DEVELOP_BRANCH: develop
  MAIN_BRANCH: main

jobs:
  pr-to-develop:
    name: "PR to develop"
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Reference: https://cli.github.com/manual/gh_pr_create
        run: |
          gh pr create --title "Backport: test..${{ env.DEVELOP_BRANCH }}" --body "Backport for test" --base ${{ env.DEVELOP_BRANCH }}

  
