name: Backport CI

on:
  push:
    branches:
      - main

env:
  DEVELOP_BRANCH: develop
  MAIN_BRANCH: main

jobs:
  pr-to-develop:
    name: "PR to develop"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Reference: https://cli.github.com/manual/gh_pr_create
        run: |
          gh pr create --title "Backport: test..${{ env.DEVELOP_BRANCH }}" --body "Backport for test" --repo $GITHUB_REPOSITORY --base ${{ env.DEVELOP_BRANCH }}
  #          gh pr create --title "Release ${{ needs.bump.outputs.version }} to ${{ env.DEVELOP_BRANCH }}" --body "$NUM_OPEN_ISSUES issues remaining" --repo $GITHUB_REPOSITORY

  
