name: Release CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  bump:
    name: 'RC version'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Tag RC version'
        id: rc-bump
        uses: 'nahuelhds/gh-action-bump-version@master'
        if: ${{ github.event.pull_request.merged != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # See: https://github.com/phips28/gh-action-bump-version?tab=readme-ov-file#usage
          bump-policy: 'ignore'
          version-type: ${{ github.event.action == 'opened' && 'preminor' || 'prerelease' }}
          # Use skip-tag if you create the tag in another step of your workflow
          # skip-tag: 'true'

      - name: 'Tag final version'
        id: final-bump
        uses: 'nahuelhds/gh-action-bump-version@master'
        if: ${{ github.event.pull_request.merged == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # See: https://github.com/phips28/gh-action-bump-version?tab=readme-ov-file#usage
          bump-policy: 'ignore'
          version-type: minor
          # Use skip-tag if you create the tag in another step of your workflow
          # skip-tag: 'true'

      - name: "cat package.json"
        run: cat package.json

      - name: 'Output Step'
        run: |
          echo TAG: ${{ steps.rc-bump.outputs.newTag || steps.final-bump.outputs.newTag}}

  build:
    needs: bump
    name: "Build ${{ needs.bump.outputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Version built: ${{ needs.bump.outputs.version }}'
        run: |
          echo TAG: ${{ needs.bump.outputs.version }}

  clean-tags:
    if: ${{ github.event.pull_request.merged == true }}
    needs:
      - bump
      - build
    name: "Clean tags"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Clean "${{ needs.bump.outputs.version }}-*" tags
        run: |
          git tag | grep ${{ needs.bump.outputs.version }}- | xargs -n 1 -I% git push origin :refs/tags/%
