name: Versioning

on:
  pull_request:
    branches:
      - develop

jobs:
  bump:
    name: 'Feat'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: "Get commit info"
        id: commit-info
        run: |
          echo "sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

      - name: 'Tag version'
        id: version-bump
        uses: 'nahuelhds/gh-action-bump-version@master'
        if: ${{ github.event.pull_request.merged != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # See: https://github.com/phips28/gh-action-bump-version?tab=readme-ov-file#usage
          bump-policy: 'ignore'
          version-type: preminor
          preid: feat
          tag-suffix: ${{ steps.commit-info.outputs.sha }}
          # For features, we want to create the tag but not changing the package.json
          skip-commit: 'true'
          # Use skip-tag if you create the tag in another step of your workflow
          # skip-tag: 'true'

      - name: "cat package.json"
        run: cat package.json

      - name: 'Output Step'
        run: |
          echo TAG: ${{ steps.version-bump.outputs.newTag }}

  build:
    needs: bump
    name: "Build ${{ needs.bump.outputs.version }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Version built: ${{ needs.bump.outputs.version }}'
        run: |
          echo TAG: ${{ needs.bump.outputs.version }}
