name: CI Semver

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  bump:
    name: 'Bump version'
    runs-on: ubuntu-latest

    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}

    if: github.event.pull_request.merged == true

    steps:
      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}

      - name: 'Bump version'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        run: |
          echo TAG: ${{ steps.version-bump.outputs.newTag }}

  build:
    name: "Build: ${{ needs.bump.outputs.new-version }}"
    runs-on: ubuntu-latest
    steps:
      - name: 'Output Step'
        run: |
          echo TAG: ${{ needs.bump.outputs.new-version }}
